### ISSUE TITLE
Where do setup_metrics go?

### ISSUE THREAD

**Issue by tpitale** [opencensus-beam/opencensus_plug#21]
I'm having trouble deciding where to place the call to `setup_metrics` as per the README:

> You also need to define metrics that will be measured, fortunately there is helper method for you, just call MyApp.MetricsPlug.setup_metrics() before running pipeline.

I checked the test and see that it's called in the test setup, so not quite the same as, say, a phoenix app.

Any thoughts or suggestions? If I figure it out, I'll send a PR to add to the README.

**Comment by hauleth** [comment]
In my application I run it within `Application.start/2` callback, but if you want you can always use `start_phase/2` as well, or any other place. Just remember that it need to be ran before your Plug will receive any request, otherwise it can fail badly.
